name: Release

on:
  push:
    tags:
      - '*'

jobs:
  gh-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: ${{ github.workspace }}/misc/release_notes.md
          generate_release_notes: true
